package detsample

import "testing"

// Cross-language conformance for the Stage-2 distance metric: the Go MAEDistance
// must reproduce byte-for-byte the value the Python reference committed to
// testdata/conformance_vectors.json (generated by
// scripts/gen_conformance_vectors.py).

type confDistanceCase struct {
	Name        string               `json:"name"`
	Executor    []map[string]float64 `json:"executor"`
	Validator   []map[string]float64 `json:"validator"`
	ExpectedMAE float64              `json:"expected_mae"`
}

func TestDistanceConformance(t *testing.T) {
	var v struct {
		Cases []confDistanceCase `json:"distance_cases"`
	}
	decodeVectors(t, &v)
	if len(v.Cases) == 0 {
		t.Fatal("no distance_cases in vectors")
	}
	for _, c := range v.Cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			// Exact equality: sorted-key summation makes the float64 accumulation
			// order identical to the Python reference (byte-exact distance).
			if got := MAEDistance(c.Executor, c.Validator); got != c.ExpectedMAE {
				t.Errorf("MAEDistance = %v, want %v", got, c.ExpectedMAE)
			}
		})
	}
}
